### ISSUE TITLE
Please document how much the wrapper covers

### ISSUE THREAD

**Issue by eudoxos** [jordens/pyflycapture2#10]
and also general principles of naming. Such as mentioning what functions are not (yet) supported, and how to translate C++ API calls to pyflycapture2 (such as that_you_use_understores InsteadOfCamelCase, properties are dicts and so on). For instance, I am wondering it Camera::SetStrobe is supported? Thanks.

**Comment by jordens** [comment]
The wrapper covers everything in https://github.com/jordens/pyflycapture2/blob/master/src/flycapture2.pyx . Methods not yet wrapped there can be added in analogy to the existing ones. Naming conventions follow standard Python. The wrapper uses the C api. You will need to find the C function corresponding to the C++ method you need. Patches for added methods and documentation are welcome.
