### ISSUE TITLE
Get EmbeddedImageInfo

### ISSUE THREAD

**Issue by DanGoodrick** [jordens/pyflycapture2#12]
Hi Robert,
First of all, I wanted to say thanks!  I've been using your software for about 6 months now and it works well (though I still can't set the framerate explicitly).  

Now, I would like to capture the embedded image info from the frames.  I have identified the following functions from the STK that would need to be implemented in the wrapper code:
fc2GetEmbeddedImageInfo
fc2SetEmbeddedImageInfo
fc2GetImageTimeStamp

The timestamp is retrieved by sending the context and a pointer to where the embedded info will go to the camera:
error=fc2GetEmbeddedImageInfo(context, &embeddedInfo)
I can check if it is available with:
embeddedInfo.timestamp.available !=0

The timestamp is turned on by setting the embeddedInfo timestamp flag onOff: 
embeddedInfo.timestamp.onOff =enableTimeStamp;

and sending it back to the camera with:
error=fc2SetEmbeddedImageInfo(context, &embeddedInfo);

The timestamp is retrieved by calling fc2GetImageTimeStamp and sending a pointer to the image array
fc2TimeStamp ts = fc2GetImageTimeStamp($rawImage);

How can I implement these functions into your wrapper project?  The functions are all defined in the _FlyCapture2Defs_C.pxd file and _FlyCapture2_C.pxd files but not in the flycapture2.pyx.  If you could explain how you wrote the other wrapper functions, I should be able to adapt them to these functions.  Thanks!  
Dan

**Comment by jordens** [comment]
Start with the `fc2{Get, Set}EmbeddedImageInfo()` functions and write `{get, set}_embedded_image_info()` methods along the lines of `{get, set}_property()` (https://github.com/jordens/pyflycapture2/blob/master/src/flycapture2.pyx#L205).

**Comment by jordens** [comment]
Or `{get, set}_trigger_mode()`, that might be a bit simpler.

**Comment by DanGoodrick** [comment]
I used …_trigger_mode() as an example.  This is my code (I made 2 functions inside the context class):

    def set_time_stamping(self.ctx):
      cdef fc2Error r
      cdef fc2EmbeddedImageInfo embeddedInfo
      with nogil:
          r = fc2GetEmbeddedImageInfo(self.ctx, &embeddedInfo)
      raise_error(r)
      if embeddedInfo.timestamp.available != 0:
          embeddedInfo.timestamp.onOff = True
      with nogil:
          r = fc2SetEmbeddedImageInfo(self.ctx, embeddedInfo)
      raise_error(r)
      return {"on_off": bool(embeddedInfo.timestamp.onOff),
              "available": embeddedInfo.available}

    def get_image_and_time_stamp(self.ctx):
      cdef fc2Error r
      cdef fc2Image rawImage;
      cdef fc2TimeStamp ts
      with nogil:
          r = fc2RetrieveBuffer( context, &rawImage )
      raise_error(r)
      ts = fc2GetImageTimeStamp( &rawImage)
      return {"Seconds": ts.cycleSeconds,
              "Ticks": ts.cycleCount,}

How does that look?  What’s the next step?
-Dan

**Comment by jordens** [comment]
No. Write thin wrappers: Write `{get, set}_embedded_image_info()` that just encapsulate their `fc2` counterparts.

**Comment by DanGoodrick** [comment]
Something like this?

	def get_embedded_image_info(self.ctx):
      cdef fc2Error r
      cdef fc2EmbeddedImageInfo embeddedInfo
      with nogil:
          r = fc2GetEmbeddedImageInfo(self.ctx, &embeddedInfo)
      raise_error(r)
      return {"onOff": bool(embeddedInfo.timestamp.onOff),
              "available": embeddedInfo.available}

**Comment by DanGoodrick** [comment]
Does the wrapper above inherit all the attributes of fc2GetImbeddedImageInfo (timestamp.onOff and .available)?

**Comment by DanGoodrick** [comment]
The other function would look like this:

    def get_image_and_time_stamp(self.ctx):
      cdef fc2Error r
      cdef fc2Image rawImage;
      with nogil:
          r = fc2GetImageTimeStamp( &rawImage)
      raise_error(r)
	  cdef fc2TimeStamp ts = r
      return {"Seconds": ts.cycleSeconds,
              "Ticks": ts.cycleCount,}

**Comment by jordens** [comment]
Almost. You should aim for these changes to be merge-able. Be thorough. If you just handle `timestamp`, nobody will be interested. Either return the `embeddedInfo` struct to the user or convert all of it to a `{"timestamp": {"available": True, "on": False}...}` dict.
Then compile it, test it, commit it.

**Comment by DanGoodrick** [comment]
Thanks for your help.  Alright...

I found definitions in the defs_C file for _fc2Timestamp, _fc2EmbeddedImageInfo, _fc2ImageMetadata and _fc2EmbeddedImageInfoProperty.  

But only _fc2Timestamp and _fc2EmbeddedImageInfo are in the flycaptuer2_C file.  Are these latter two the only functions I need to wrap?  

Each is a struct with a handful of members that would be returned in a dict.

**Comment by DanGoodrick** [comment]
Would this be correct for get_embedded_image_info?

    def get_embedded_image_info(self):
        cdef fc2Error r
        cdef fc2EmbeddedImageInfo pInfo
        with nogil:
            r = fc2GetEmbeddedImageInfo(self.ctx, &pInfo)
        raise_error(r) #not in fc2GetTriggerMode??
        return {'timestamp': pInfo.timestamp,
                'gain': pInfo.gain,
                'shutter': pInfo.shutter,
                'brightness': pInfo.brightness,
                'exposure': pInfo.exposure,
                'whiteBalance': pInfo.whiteBalance,
                'frameCounter': pInfo.frameCounter,
                'strobePattern': pInfo.strobePattern,
                'GPIOPinState': pInfo.GPIOPinState,
                'ROIPosition': pInfo.ROIPosition}

**Comment by jordens** [comment]
You have to wrap the functions that you want to use. Yes.
If you want to return a dict, return it in the format that I suggested. Don't return the `...Property` as values but unpack them. And pythonize the strings (`.GPIOPinState` -> `"gpio_pin_state") as done in the other methods.

**Comment by DanGoodrick** [comment]
So each struct attribute of get_embedded_image_info would have two dictionary keys?  

    def get_embedded_image_info(self):
        cdef fc2Error r
        cdef fc2EmbeddedImageInfo pInfo
        with nogil:
            r = fc2GetEmbeddedImageInfo(self.ctx, &pInfo)
        raise_error(r) #not in fc2GetTriggerMode??
        return {'timestamp_available': bool(pInfo.timestamp.available),
                'timestamp_onOff':bool(pInfo.timestamp.onOff),
...

**Comment by jordens** [comment]
convert all of it to a {"timestamp": {"available": True, "on": False}...} dict.
