### ISSUE TITLE
Will pyflycapture2 work with GigE camera

### ISSUE THREAD

**Issue by LMSAas** [jordens/pyflycapture2#17]
Hi,
I have a gigE camera from point grey. When I run 
`import flycapture2`
I get the following error
`flycapture2.pyx in init flycapture2 (src/flycapture2.c:10316)()

ValueError: level must be >= 0`

The C++ examples in the point-grey sdk works fine.
Is this related to support for gigE camera in this package??

**Comment by jordens** [comment]
gigE cameras shoud be fine. pyflycapture is agnostic to what flycapture2 supports or does not support.
That error sounds like a miscompilation (windows? msvc/msys vs gcc?) or mismatching python versions (different python version used when compiling vs using, multiple pyfycapture modules installed) to me.

**Comment by jordens** [comment]
@LMSAas ping

**Comment by gabrielguerrer** [comment]
@jordens I have upgraded pyflycapture2 to support Gige in more depth, being able to setup packet size and packet delay for example. I would like to show the code and contribute.

**Comment by jordens** [comment]
@gabrielguerrer thanks!

**Comment by LMSAas** [comment]
Thank you very much! I will try it as soon as I get the time.

Lars
