### ISSUE TITLE
Installing on arm processor

### ISSUE THREAD

**Issue by EvilGarfield** [jordens/pyflycapture2#23]
Hi!

Thank you for oyur wrappe that proved very useful. I use it on Linux without problem. I now want to use the camera on a RPi3 but when installing the wrapper, I get the following error: 

`running install

running bdist_egg

running egg_info

writing pyflycapture2.egg-info/PKG-INFO
writing requirements to pyflycapture2.egg-info/requires.txt
writing dependency_links to pyflycapture2.egg-info/dependency_links.txt
writing top-level names to pyflycapture2.egg-info/top_level.txt
reading manifest file 'pyflycapture2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyflycapture2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_ext
skipping 'src/flycapture2.c' Cython extension (up-to-date)
building 'flycapture2' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/flycapture/C -IC:/Program Files/Point Grey Research/FlyCapture2/include/C -I/home/droppi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -I/home/droppi/.virtualenvs/cv/include/python3.5m -c src/flycapture2.c -o build/temp.linux-armv7l-3.5/src/flycapture2.o
src/flycapture2.c:432:31: fatal error: FlyCapture2Defs_C.h: No such file or directory
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
`

Are you aware of such an issue? Would you have a workaround?

Thank you in advance
Best

**Comment by jordens** [comment]
https://github.com/jordens/pyflycapture2#install-point-grey-flycapture2-library

**Comment by jordens** [comment]
check that you have the heades in the usual locations (`/usr/include/...`) or adjust  https://github.com/jordens/pyflycapture2/blob/master/setup.py

**Comment by ethanlarochelle** [comment]
@EvilGarfield I tried this a few months ago and kept hitting different issues. I know this doesn't really help, but I had an Intel MinnowBoard Max available and it works well on that without making changes. The physical size is similar to the Pi and has USB3 and SATA support.

**Comment by EvilGarfield** [comment]
I think that the problem is that FlyCapture is not installed the same was on an ARM architecture than on other. So I copied my files from the desktop PC to the Pi on /usr/include. This solved my error but now I'm stuck a bit farther down the road. 

`
running install
running bdist_egg
running egg_info
writing pyflycapture2.egg-info/PKG-INFO
writing requirements to pyflycapture2.egg-info/requires.txt
writing dependency_links to pyflycapture2.egg-info/dependency_links.txt
writing top-level names to pyflycapture2.egg-info/top_level.txt
reading manifest file 'pyflycapture2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyflycapture2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_ext
skipping 'src/flycapture2.c' Cython extension (up-to-date)
building 'flycapture2' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/flycapture/C -IC:/Program Files/Point Grey Research/FlyCapture2/include/C -I/home/droppi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -I/home/droppi/.virtualenvs/cv/include/python3.5m -c src/flycapture2.c -o build/temp.linux-armv7l-3.5/src/flycapture2.o
In file included from src/flycapture2.c:433:0:
/usr/include/flycapture/C/FlyCapture2_C.h:395:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   fc2ForceAllIPAddressesAutomatically();
   ^
/usr/include/flycapture/C/FlyCapture2_C.h:1533:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   ResetStats();
   ^
In file included from /home/droppi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /home/droppi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/droppi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/flycapture2.c:437:
/home/droppi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
src/flycapture2.c: In function ‘__pyx_pf_11flycapture2_5Image_4__array__’:
src/flycapture2.c:7139:36: warning: passing argument 1 of ‘(PyObject * (*)(PyTypeObject *, PyArray_Descr *, int,  npy_intp *, npy_intp *, void *, int,  PyObject *))*(PyArray_API + 376u)’ from incompatible pointer type [-Wincompatible-pointer-types]
   __pyx_t_1 = PyArray_NewFromDescr(((PyObject *)__pyx_ptype_5numpy_ndarray), __
                                    ^
src/flycapture2.c:7139:36: note: expected ‘PyTypeObject * {aka struct _typeobject *}’ but argument is of type ‘PyObject * {aka struct _object *}’
creating build/lib.linux-armv7l-3.5
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.5/src/flycapture2.o -LC:/Program Files/Point Grey Research/FlyCapture2/lib64/C -lflycapture-c -o build/lib.linux-armv7l-3.5/flycapture2.cpython-35m-arm-linux-gnueabihf.so
/usr/bin/ld: cannot find -lflycapture-c
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

`

I am fairly new to programming and Linux in general and I struggle to understand the rpoblem. I cannot find this -lflycapture-c even on my Desktop

**Comment by jordens** [comment]
libflycapture-c is one of the pointgrey packages

**Comment by jordens** [comment]
@EvilGarfield is this resolved now?

**Comment by chelsell** [comment]
@jordens I had the same problem, like you say it is fixed by moving the contents of flycapture.2.9.3.43_armhf/lib/C (including libflycapture-c.so) to /usr/lib. It's easy to miss this  because the pointgrey installation instructions don't say to copy the contents of this C/ directory to /usr/lib. Might be worth documenting in the installation instructions.

**Comment by jordens** [comment]
@chelsell Thanks! I don't really use pyflycapture2 much anymore. Could you write a few lines of instructions with the correct files and the correct locations?

**Comment by chelsell** [comment]
@jordens Happily! One somewhat unrelated question though--you mention that there is now PointGrey support for a python flycap wrapper, but I can't find it. Would you mind sharing a link?

**Comment by jordens** [comment]
[here](http://r20.rs6.net/tn.jsp?f=001IINPUkAYLFJmbNEYzk8USrWRnwzTV8MNeHvXVgXNi6Q-CiJVLXeCohAF4lHxtc5yEVWl7EdzQqBKEBjTjARIXiByKKYF7RbyxDhmMJuPD7ha_lwjsTHZpcUW5vqhUELNIaaYixLhui9jKBADGGMDv6feQ29jn7zPXJqebPF9_ZiEJNSJ-tYgmH_YTdJeYshGb4iCDwHtTt8=&c=YfFD515orClV4RDsYSrOsYbRkFB_gLwO4UrfsCEeKP3y9gD4o5Xhcw==&ch=M805XXgkDdh7kGgGc3Hc5hVfIbAW38fTkopLdaSqgttVk3NQFYQbIA==)
and [here](http://r20.rs6.net/tn.jsp?f=001IINPUkAYLFJmbNEYzk8USrWRnwzTV8MNeHvXVgXNi6Q-CiJVLXeCosbCX38JTnx7C6tSjkfZGdLCKJxoz9g0DPxLkTfZp_FpcoMbPnRKzjukkDNJ3TPAD_VEIVCYGmZiPj6g2JSs0EAVSeng6K-aLoFWiyu3RwyVo4LkjqrBTs0B5TKe3VuVDKnLMYINC3tch9tizEl8xTNya61P8eYKvMWviesmV6EAETYOCv6sJou0ueYlafsBPWic1X6SFxbs&c=YfFD515orClV4RDsYSrOsYbRkFB_gLwO4UrfsCEeKP3y9gD4o5Xhcw==&ch=M805XXgkDdh7kGgGc3Hc5hVfIbAW38fTkopLdaSqgttVk3NQFYQbIA==)
and [here](http://r20.rs6.net/tn.jsp?f=001IINPUkAYLFJmbNEYzk8USrWRnwzTV8MNeHvXVgXNi6Q-CiJVLXeCosbCX38JTnx7C6tSjkfZGdLCKJxoz9g0DPxLkTfZp_FpcoMbPnRKzjukkDNJ3TPAD_VEIVCYGmZiPj6g2JSs0EAVSeng6K-aLoFWiyu3RwyVo4LkjqrBTs0B5TKe3VuVDKnLMYINC3tch9tizEl8xTNya61P8eYKvMWviesmV6EAETYOCv6sJou0ueYlafsBPWic1X6SFxbs&c=YfFD515orClV4RDsYSrOsYbRkFB_gLwO4UrfsCEeKP3y9gD4o5Xhcw==&ch=M805XXgkDdh7kGgGc3Hc5hVfIbAW38fTkopLdaSqgttVk3NQFYQbIA==)
supposedly.

**Comment by chelsell** [comment]
@jordens Thanks
