### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by villanuevab** [jordens/pyflycapture2#29]
Is this package compatible with Python 3.x? I get the following error upon trying to import the module: 
```
Traceback (most recent call last):
  File "pg_inference.py", line 14, in <module>
    import flycapture2 as fc2
  File "flycapture2.pyx", line 22, in init flycapture2 (src/flycapture2.c:10316)
ValueError: level must be >= 0
```

**Comment by jordens** [comment]
Yes. It is.
You'll have to debug that error. It looks more like cython/numpy version issues.

**Comment by villanuevab** [comment]
What versions of cython, numpy, and python should be used? I have: 
- cython 0.26
- numpy v1.11.0
- python 3.5.2

I'm not familiar with any version issues, and would appreciate any further insight. 
Thank you for your time!

**Comment by villanuevab** [comment]
So, I am able to import `pyflycapture2` if I install via `pip3 install pyflypackage2` instead of installing from sources (i.e., this repo), but  it does not seem to have the same functions available as in this repo: 
```
>>> import pyflycapture2 as fc2
>>> c = fc2.Context()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyflycapture2' has no attribute 'Context'
```

Is the underlying code different between this repo and the pip package from https://pypi.python.org/pypi/pyflycapture2 ?

**Comment by villanuevab** [comment]
If you try to install the package via pip, i.e., 
```pip3 install pyflycapture2``` 
the version installed is old; not good. 

If you just clone the git repo and run 
```python3 setup.py install```
the library is not installed correctly; not good.

Telling pip to use the git repo to install, i.e., 
```sudo pip install git+https://github.com/jordens/pyflycapture2.git```
fixes my previously mentioned errors and installs the package correctly.

**Comment by jordens** [comment]
`pypi` will give you released versions. The other commands give you whatever the current development is.
