### ISSUE TITLE
Compiling erorr with SyntaxError: encoding problem utf8

### ISSUE THREAD

**Issue by dujianyi** [jordens/pyflycapture2#4]
Hi,

I am trying to compile the package in CMD with

python setup.py build install

And got the following error messages.

C:\pip\pyflycapture2-master>python setup.py build install
  File "setup.py", line 2
SyntaxError: encoding problem: utf8

And then I changed "utf8" (w/o quotes) to "utf-8", everything works.

Hope it helps.

**Comment by jordens** [comment]
weird. i can't reproduce it. and the standard syntax is `-*- coding: utf8 -*-` without quotes AFAICT

**Comment by jordens** [comment]
this might be resolved with commit ada52e2

**Comment by Pickersgill** [comment]
Very helpful, thank you.

**Comment by sohjag** [comment]
Super helpful this! Thanks!
