### ISSUE TITLE
I wonder if there are more sample examples

### ISSUE THREAD

**Issue by dujianyi** [jordens/pyflycapture2#5]
Hey,

I wonder if more sample examples could be provided, I am currently using this wrapper with PyQt5 to show live video, but O really can't understand how to figure it out.

Thank you!

**Comment by blah73** [comment]
Yes examples would go a long way.  I'm considering purchasing a camera for use with this software.  I'm planning to go for python first and fall back to the supported C# if I can't get library working.  I will gladly contribute my own examples if/when I have them but first I need to get off the ground.

**Comment by jordens** [comment]
Here is another example https://github.com/jordens/bullseye/blob/master/bullseye/flycapture2_capture.py

**Comment by dujianyi** [comment]
Hey Jordens,

Thank you for the update! But I don't think it helps with my problem. Now I have an array from "retrieve_buffer" with size of 1024 * 768, I wonder how I can display it on the screen? Is it grey picture?

Thank you!

**Comment by jordens** [comment]
there is no problem here. the array is just what your pixels see. if you have r-g-b pixels you have to figure out how to do the interpolation. plotting pictures is done with any other library.

**Comment by blah73** [comment]
Thanks Jordens that makes sense.  So in theory I should be able to plug the RGB array returned from this library into PIL's putdata function and then save it.  Would you prefer such a script be pull requested to your repo here or should I keep it separate?

**Comment by jordens** [comment]
it is not an rgb array. if you sensor is rgb, the data is the bayer grid. this is all explained in the documentation. i don't think "saving an array with pil" is a helpful addition.
