### ISSUE TITLE
Color images

### ISSUE THREAD

**Issue by physicsG** [jordens/pyflycapture2#9]
I  am working with the CMLN-13S2C-CS which is able to show RGB images using the flycap application. However, I cannot get it to grab color images using pyflycapture2. The FlyCapture SDK should be able to grab color images, so is there an option with pyflycapture2 to get color images?

**Comment by jordens** [comment]
Color sensors data needs to be demosaic'ed to get a color image. Determine the necessary functions and wrap them if they exist.

**Comment by physicsG** [comment]
I just assumed they exist since FlyCap can show RGB images. I have no idea
where to start.

**Comment by jordens** [comment]
The API documentation for flycapture2 (from pointgrey) should have the required information.

**Comment by jordens** [comment]
I would guess that the required methods are among these from https://github.com/jordens/pyflycapture2/blob/master/src/_FlyCapture2_C.pxd:

```
fc2SetDefaultColorProcessing
fc2SetDefaultOutputFormat
fc2ConvertImage
fc2SetImageDimensions
```

They would need wrapping in https://github.com/jordens/pyflycapture2/blob/master/src/flycapture2.pyx similar to how the other functions are wrapper.

**Comment by physicsG** [comment]
So what I have to do is sort of the following?

    def SetDefaultColorProcessing(self, something else):
        cdef fc2Error r
        with nogil:
            r = fc2SetDefaultColorProcessing(self.ctx)
        raise_error(r)

But I don't know what the functions look like and all I could find was this old documentation http://www.cs.unc.edu/Research/stc/FAQs/Cameras_Lenses/PtGrey/pgrFlyCaptureManual-v1.4.pdf

**Comment by jordens** [comment]
I don't have a color ccd camera. You should download the point grey flycapture2 api documentation. That PDF seems old.

**Comment by fonty422** [comment]
@physicsG, I simply replaced the whole `def __array__ (self)` section in flycapture2.pyx with that on http://stackoverflow.com/questions/32853813/using-python-binding-for-flycapture-to-retrieve-color-image provided by Rene Juuse (the second response), along with the `c.set_format7_configuration(fc2.MODE_0, 320, 240, 1280, 720, fc2.PIXEL_FORMAT_MONO8)` command and it ran perfectly for me with a grasshopper3-Colour with 2048x2048.
